// Parsing :: Grammar, GrammarBuilder, Node, Parser...

#ifndef PARSER_HPP_
#define PARSER_HPP_

#include <deque>
#include <limits>
#include <optional>
#include <unordered_map>
#include <variant>
#include <common.hpp>
#include "generator.hpp"
#include "lexer.hpp"

namespace Parsing {

  // Preprocessed context-free grammar for use by `Parser`.
  struct Grammar {
    struct Rule {
      std::pair<Symbol, Precedence> lhs;
      std::vector<std::pair<Symbol, Precedence>> rhs;
    };
    Symbol numSymbols;                            // Number of symbols = (Maximum symbol ID occured in rules) + 1.
    Symbol startSymbol;                           // Starting symbol ID.
    Symbol ignoredSymbol;                         // Ignored symbol ID.
    std::vector<Rule> rules;                      // Rule ID -> (LHS symbol, RHS symbols).
    std::vector<std::optional<size_t>> emptyRule; // LHS symbol ID -> empty rule ID.
    std::vector<size_t> sorted;                   // Indices of non-empty rules, sorted by LHS symbol.
    std::vector<size_t> firstRule;                // LHS symbol ID -> index in `sorted`.
  };

  // Grammar preprocessor.
  class GrammarBuilder {
  public:
    auto withStartSymbol(Symbol value) -> GrammarBuilder&;
    auto withIgnoredSymbol(Symbol value) -> GrammarBuilder&;
    auto withRule(std::pair<Symbol, Precedence> lhs, std::vector<std::pair<Symbol, Precedence>> const& rhs)
      -> GrammarBuilder&;

    // Constructs a well-formed `Grammar`.
    auto make() -> Grammar const;

  private:
    Symbol _startSymbol = 0;
    Symbol _ignoredSymbol = 0;
    std::vector<Grammar::Rule> _rules;
  };

  // An Earley state emitted by a parser.
  // All pointers should be non-empty and valid.
  struct Node {
    struct State {
      size_t begin;    // Start index in sentence.
      size_t end;      // End index in sentence.
      size_t rule;     // Production rule ID.
      size_t progress; // Index in production rule.
      // Required since `State`s are used as keys to `std::unordered_map`.
      auto operator==(State const&) const -> bool = default;
      // Required since `State`s are used as keys to `std::unordered_map`.
      struct Hasher {
        auto operator()(State const& s) const -> size_t { return hashAll(s.begin, s.end, s.rule, s.progress); }
      };
    };
    State state;                                                     // Payload.
    std::vector<std::pair<Node*, std::variant<Node*, Token*>>> next; // Forward links.
    std::vector<std::pair<Node*, std::variant<Node*, Token*>>> prev; // Backward links.
  };

  /*
  // Error generated by parser.
  struct ParserError {
    size_t begin;
    size_t end;
    std::vector<Symbol> expected;
    std::optional<Symbol> got;
  };
  */

  // Earley parser!
  // This is more suitable for left-recursive grammars than right-recursive ones.
  class Parser {
  public:
    // Given references must be valid over the `Parser`'s lifetime.
    Parser(Grammar const& grammar, Generator<std::optional<Token>>& lexer):
      _grammar(grammar),
      _lexer(lexer) {}

    auto eof() const -> bool { return _lexer.eof(); }
    auto advance() -> bool;

    // Retrieves results.
    auto tokens() const -> std::deque<Token> const& { return _tokens; }
    auto nodes() const -> std::deque<std::deque<Node>> const& { return _nodes; }

    // Debug output.
    auto showState(Node const& ls, std::vector<std::string> const& names) const -> std::string;
    auto showStates(std::vector<std::string> const& names) const -> std::string;

  private:
    Grammar const& _grammar;                 // Grammar.
    Generator<std::optional<Token>>& _lexer; // Token stream.
    std::deque<Token> _tokens;               // Parsed tokens.
    std::deque<std::deque<Node>> _nodes;     // The DP array, aka. "shared packed parse forest (SPPF)".

    // Map for state deduplication: state -> node.
    std::unordered_map<Node::State, Node*, Node::State::Hasher> _map;
    // Map of nonempty completion candidates: (end position, next symbol) -> node.
    std::unordered_multimap<std::pair<size_t, Symbol>, Node*, PairHasher> _completions;

    auto _nextToken() -> std::optional<Token>;
    auto _node(size_t begin, size_t end, size_t rule, size_t progress) -> Node*;
    auto _transition(Node* prev, std::variant<Node*, Token*> child, Node* next) -> void;
    auto _run() -> bool;
  };

}

#endif // PARSER_HPP_
